//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animals()
        {
            this.AnimalAssessments = new HashSet<AnimalAssessments>();
            this.AnimalPedigree = new HashSet<AnimalPedigree>();
            this.AnimalPedigree1 = new HashSet<AnimalPedigree>();
            this.AnimalPedigree2 = new HashSet<AnimalPedigree>();
            this.Breedings = new HashSet<Breedings>();
            this.Breedings1 = new HashSet<Breedings>();
            this.Exhibitions = new HashSet<Exhibitions>();
            this.MediaLinks = new HashSet<MediaLinks>();
            this.ProductivityRecords = new HashSet<ProductivityRecords>();
            this.VeterinaryEvents = new HashSet<VeterinaryEvents>();
        }
    
        public int Id { get; set; }
        public int TreeId { get; set; }
        public string Nickname { get; set; }
        public string InventoryNumber { get; set; }
        public int SpeciesId { get; set; }
        public Nullable<int> BreedId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public int GenderId { get; set; }
        public Nullable<bool> IsCastrated { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public string DeathPlace { get; set; }
        public string DeathReason { get; set; }
        public Nullable<bool> IsAlive { get; set; }
        public Nullable<int> PedigreeClassId { get; set; }
        public Nullable<decimal> BreedingValue { get; set; }
        public Nullable<bool> IsBreedingStock { get; set; }
        public Nullable<decimal> HeightAtWithers { get; set; }
        public Nullable<decimal> ChestGirth { get; set; }
        public Nullable<decimal> BodyLength { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string ChipNumber { get; set; }
        public string GeneticDiseases { get; set; }
        public Nullable<System.DateTime> DNATestDate { get; set; }
        public string DNAResults { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Description { get; set; }
        public string ProfilePhotoPath { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalAssessments> AnimalAssessments { get; set; }
        public virtual AnimalGenders AnimalGenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalPedigree> AnimalPedigree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalPedigree> AnimalPedigree1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalPedigree> AnimalPedigree2 { get; set; }
        public virtual Breeds Breeds { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual PedigreeClasses PedigreeClasses { get; set; }
        public virtual Species Species { get; set; }
        public virtual FamilyTrees FamilyTrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Breedings> Breedings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Breedings> Breedings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exhibitions> Exhibitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaLinks> MediaLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductivityRecords> ProductivityRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeterinaryEvents> VeterinaryEvents { get; set; }
    }
}
