//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalAssessments
    {
        public int Id { get; set; }
        public int AnimalId { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public int ClassId { get; set; }
        public Nullable<decimal> OverallScore { get; set; }
        public Nullable<decimal> ExteriorScore { get; set; }
        public Nullable<decimal> ProductivityScore { get; set; }
        public Nullable<decimal> OffspringScore { get; set; }
        public string CommissionMembers { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public string Notes { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual PedigreeClasses PedigreeClasses { get; set; }
        public virtual Users Users { get; set; }
    }
}
