//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breedings
    {
        public int Id { get; set; }
        public int TreeId { get; set; }
        public int MaleId { get; set; }
        public int FemaleId { get; set; }
        public System.DateTime BreedingDate { get; set; }
        public Nullable<System.DateTime> ExpectedBirthDate { get; set; }
        public Nullable<System.DateTime> ActualBirthDate { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public Nullable<int> OffspringCount { get; set; }
        public Nullable<int> AliveCount { get; set; }
        public string Notes { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Animals Animals1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual FamilyTrees FamilyTrees { get; set; }
    }
}
