//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibitions
    {
        public int Id { get; set; }
        public int TreeId { get; set; }
        public int AnimalId { get; set; }
        public string ExhibitionName { get; set; }
        public System.DateTime ExhibitionDate { get; set; }
        public string Location { get; set; }
        public string Result { get; set; }
        public string JudgeName { get; set; }
        public Nullable<int> Rating { get; set; }
        public string CertificateNumber { get; set; }
        public string Notes { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Users Users { get; set; }
        public virtual FamilyTrees FamilyTrees { get; set; }
    }
}
