//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaLinks
    {
        public int Id { get; set; }
        public int MediaFileId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public Nullable<int> StoryId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual MediaFiles MediaFiles { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Stories Stories { get; set; }
    }
}
