//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaFiles()
        {
            this.MediaLinks = new HashSet<MediaLinks>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public long FileSize { get; set; }
        public int MediaTypeId { get; set; }
        public string Description { get; set; }
        public int UploadedByUserId { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public bool IsProfilePhoto { get; set; }
    
        public virtual MediaTypes MediaTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaLinks> MediaLinks { get; set; }
    }
}
