//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenealogyUnifiedDBEntities : DbContext
    {
        public GenealogyUnifiedDBEntities()
            : base("name=GenealogyUnifiedDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalAssessments> AnimalAssessments { get; set; }
        public virtual DbSet<AnimalGenders> AnimalGenders { get; set; }
        public virtual DbSet<AnimalPedigree> AnimalPedigree { get; set; }
        public virtual DbSet<Animals> Animals { get; set; }
        public virtual DbSet<Breedings> Breedings { get; set; }
        public virtual DbSet<Breeds> Breeds { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Exhibitions> Exhibitions { get; set; }
        public virtual DbSet<FamilyTrees> FamilyTrees { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<MediaFiles> MediaFiles { get; set; }
        public virtual DbSet<MediaLinks> MediaLinks { get; set; }
        public virtual DbSet<MediaTypes> MediaTypes { get; set; }
        public virtual DbSet<PedigreeClasses> PedigreeClasses { get; set; }
        public virtual DbSet<PersonRelationships> PersonRelationships { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<ProjectTypes> ProjectTypes { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Stories> Stories { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
