//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRelationships
    {
        public int Id { get; set; }
        public int Person1Id { get; set; }
        public int Person2Id { get; set; }
        public int RelationshipType { get; set; }
        public Nullable<int> Direction { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedByUserId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Persons Persons1 { get; set; }
    }
}
