//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductivityRecords
    {
        public int Id { get; set; }
        public int AnimalId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<decimal> MilkYield { get; set; }
        public Nullable<decimal> FatContent { get; set; }
        public Nullable<decimal> ProteinContent { get; set; }
        public string RecordType { get; set; }
        public string Notes { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Users Users { get; set; }
    }
}
