//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeterinaryEvents
    {
        public int Id { get; set; }
        public int AnimalId { get; set; }
        public System.DateTime EventDate { get; set; }
        public int EventTypeId { get; set; }
        public string MedicineName { get; set; }
        public string Dosage { get; set; }
        public Nullable<int> WithdrawalDays { get; set; }
        public string VetName { get; set; }
        public Nullable<System.DateTime> NextDueDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Notes { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Users Users { get; set; }
        public virtual VeterinaryEventTypes VeterinaryEventTypes { get; set; }
    }
}
